# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d323578efea61d5c79ff60a02d4ef5596f84178b989ecd60f7f9ddb44264cfefa18fe5c808843453c6ff11bace05cc8e681c23162a61ddc1ce100d5dcaf87e2e

test:
  secret_key_base: f20b1636c899b1b1610bd652adb3b6c4fb55f04e5e3d23e05bdfe214e42474d07025f65d4ce67446f052df684415025afee0d4305334e4aabcd29867498894a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
